Trailer list

In [ ]:
import pandas as pd, numpy as np
import matplotlib.pyplot as plt, seaborn as sns
%matplotlib inline

In [13]:
import os
os.getcwd()

'C:\\Users\\harleyquinn\\Desktop\\docu3c\\bollywood_movie_analysis\\trailer-data'

In [14]:
os.chdir("C:\\Users\\harleyquinn\\Desktop\\docu3c\\bollywood_movie_analysis\\trailer-data")

In [15]:
df=pd.read_csv('trailers_list.csv',on_bad_lines='skip')  


In [16]:
df

movie_name  year-of-release  trailer  movie
0           dedh_ishqiya             2014        1      0
1    love_sex_aur_dhokha             2010        1      0
2                 newton             2017        1      0
3     band_baaja_baaraat             2010        1      0
4     the_blueberry_hunt             2016        1      0
..                   ...              ...      ...    ...
872              warning             2013        1      0
873             ranbanka             2015        1      0
874           sadda_adda             2012        1      0
875           loveshhuda             2016        1      0
876          housefull_3             2016        1      0

[877 rows x 4 columns]

In [17]:
df.fillna("1", inplace = True)

In [18]:
df = df.dropna(axis=1)

print(df)

              movie_name  year-of-release  trailer  movie
0           dedh_ishqiya             2014        1      0
1    love_sex_aur_dhokha             2010        1      0
2                 newton             2017        1      0
3     band_baaja_baaraat             2010        1      0
4     the_blueberry_hunt             2016        1      0
..                   ...              ...      ...    ...
872              warning             2013        1      0
873             ranbanka             2015        1      0
874           sadda_adda             2012        1      0
875           loveshhuda             2016        1      0
876          housefull_3             2016        1      0

[877 rows x 4 columns]


In [19]:
df.isna().sum()

movie_name         0
year-of-release    0
trailer            0
movie              0
dtype: int64

In [20]:
X=df.drop('year-of-release',axis=1)
y=df['year-of-release']

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [21]:
from sklearn.ensemble import RandomForestRegressor
classifier = RandomForestRegressor(random_state = 0)

In [22]:
import category_encoders as ce

In [23]:
encoder = ce.OrdinalEncoder(cols=['movie_name'])


X_train = encoder.fit_transform(X_train)

X_test = encoder.transform(X_test)

In [24]:
X_train

movie_name  trailer  movie
487           1        1      0
644           2        1      0
212           3        1      0
432           4        1      0
79            5        1      0
..          ...      ...    ...
106         649        1      0
270         650        1      0
860         651        1      0
435         652        1      0
102         653        1      0

[657 rows x 3 columns]

In [25]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(random_state = 0)
classifier.fit(X_train, Y_train)

RandomForestClassifier(random_state=0)

In [26]:
Y_pred = classifier.predict(X_test)

In [27]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test, Y_pred)

print ("Confusion Matrix : \n", cm)

Confusion Matrix : 
 [[ 0  0  0  0  0  0  0  0 14  0]
 [ 0  0  0  0  0  0  0  0 20  0]
 [ 0  0  0  1  0  0  0  0 15  0]
 [ 0  0  0  0  0  0  0  0 23  0]
 [ 0  0  0  0  0  0  0  0 17  0]
 [ 0  0  0  0  0  0  0  0 16  0]
 [ 0  0  0  0  0  0  0  0 32  0]
 [ 0  0  0  0  0  0  0  0 26  0]
 [ 0  0  0  0  0  0  0  0 28  0]
 [ 0  0  0  0  0  0  0  0 28  0]]


In [28]:
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(Y_test, Y_pred))

Accuracy :  0.12727272727272726


In [29]:
trailers="Accuracy : ", accuracy_score(Y_test,Y_pred)

In [30]:
trailers

('Accuracy : ', 0.12727272727272726)